### ISSUE TITLE
brewers and beers not working

### ISSUE THREAD

**Issue by moxx** [devisephp/example#3]
Hi,

on an fresh installation on brewers you got following error -> 
```
Undefined variable: brewersAlphabeticallyGrouped (View: /home/vagrant/code/devise_example/resources/views/templates/brewers/index.blade.php)
````

on beers ->
```
Undefined variable: beers (View: /home/vagrant/code/devise_example/resources/views/templates/beers/index.blade.php)
```

**Comment by dolbex** [comment]
@moxx - We will be looking into this issue today.

**Comment by dolbex** [comment]
@moxx Probably what is happening is your /config/devise/templates.php file is being overwritten during the install. If you put the original one from the repo in there it will most likely fix that. I'm going to see if we can make this a little more obvious.
