### ISSUE TITLE
Can't install Brewers and Beers

### ISSUE THREAD

**Issue by fredbombadil** [devisephp/example#4]
Tried using 5.0.*, since 5.1 is a lost cause, and the nearest I got was copying the example-master files into the laravel project's directory, running composer update, installing via browser/cl, but can't run php artisan migrate because of table not found error. 

Tried rolling back install, then I can run php artisan migrate but db:seeds always fails. 

When will this be updated for 5.1?

**Comment by dolbex** [comment]
I will open a ticket and we will discuss in tomorrow morning's traffic meeting. I'll post here as soon as it gets on the schedule on when you can expect it @fredbombadil

**Comment by fredbombadil** [comment]
Great, I'll be looking forward to it. Devise seems very promising.

**Comment by fredbombadil** [comment]
Great, I'll be looking forward to it. Devise seems very promising.

**Comment by dolbex** [comment]
Thanks @fredbombadil! We're working on hard on it. You can expect the update later today. @kdocki is working his magic.
