### ISSUE TITLE
Undefined variables

### ISSUE THREAD

**Issue by fredbombadil** [devisephp/example#5]
Got the homepage opening on the newly updated 5.1 example, but running into issues:

"Undefined variable: brewersAlphabeticallyGrouped" on /brewers/
 "Undefined variable: brewer"  on /brewers/{brewer-id}  and
"Undefined variable: beers" on /beers

I tried a few workarounds (adding index() to BeerController, etc) but no dice.

**Comment by dolbex** [comment]
Fred - I talked to the guys this morning and it looks like they are still working. Hit some bug on Friday (not sure what it was - I was out)

**Comment by dolbex** [comment]
@fredbombadil - Recheckout the repo. We think you overwrote /config/devise/templates.php
