### ISSUE TITLE
Vendor folder missing

### ISSUE THREAD

**Issue by chrisvidal** [devisephp/example#6]
Hi there,
thanks for this,
after running the command composer update, the folder "vendor" is missing for the auload features.

**Comment by Pandahisham** [comment]
same problem here

**Comment by knolaust** [comment]
Same. Really wanted to checkout the demo, but all sorts of errors.

**Comment by christophengelmayer** [comment]
I just figured out a workaround to install the Demo page:
1. Remove the `"scripts": {...},` section from the composer.json file (Copy it to the clipboard, we'll need it later!).
2. Run `$ composer update`
3. Run `$ php -r "copy('.env.example', '.env');"`
4. Open the .env file and change the third line to `APP_KEY=SomeRandomStringWith32Characters`
5. Run `$ php artisan key:generate`
6. Insert `"scripts": {...},` section into the composer.json file again
7. Run `$ composer update` again

**Comment by dolbex** [comment]
@slashadmin Another way to do this is just run 

```
composer update --no-scripts
```

**Comment by maesklaas** [comment]
I have the same problem but the workaround doesn't work for me, when i get to point 5 php artisan key:generate i get the same error:

Warning: require(/Users/me/projects/beer/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /Users/me/projects/beer/bootstrap/autoload.php on line 17

Fatal error: require(): Failed opening required '/Users/me/projects/beer/bootstrap/../vendor/autoload.php' (include_path='.:') in /Users/me/projects/beer/bootstrap/autoload.php on line 17

How can i fix this?
