### ISSUE TITLE
PHP Parse error:  syntax error, unexpected 'class'  $kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

### ISSUE THREAD

**Issue by manoj10029** [devisephp/example#7]
I upload project on share host server and got following error

Error on  public/index.php file as follow

PHP Parse error:  syntax error, unexpected 'class' 

 $kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

PHP version 5.6

**Comment by cinco-de-mauro** [comment]
This is not an issue with Devisephp. The file your error refers to is the index file of Laravel.

Although you've posted that your php version is 5.6, I think your app is using an older version.

The "Kernel::class" syntax is using a php feature introduced in 5.5 called "Class name resolution via ::class" (http://php.net/manual/en/migration55.new-features.php#migration55.new-features.class-name).

I suggest debugging the version of php you are currently running and upgrading from there.

**Comment by manoj10029** [comment]
Thank you pistonhonda. No I overcome from issue.

**Comment by ghost** [comment]
how did u overcome the issue, please tell.

**Comment by manoj10029** [comment]
I have upgrade my PHP version 5.5 to v5.6.  On share hosting, we need to change .htaccess, add new line on top of it.

---

.htaccess : 
            AddHandler application/x-httpd-php56 .php .php5 .php4 .php3

---

For this I had got reference from this site.

https://www.siteground.com/kb/how_to_have_different_php_versions/

http://php.net/manual/en/function.phpversion.php

**Comment by ghost** [comment]
i wish i could do that, but i can not update the php version.in our server php version is 5.5.38 . laravel 5.2 and 5.1 requires 5.5.9= or above. (as far as i know)

**Comment by ghost** [comment]
Thank you

**Comment by cinco-de-mauro** [comment]
@tanjilbhuiyan although manoj10029 upgraded to 5.6 it should not be required.

The "Class name resolution via ::class" (http://php.net/manual/en/migration55.new-features.php#migration55.new-features.class-name) feature is available in 5.5.x.

Have you tried testing the feature `echo ClassName::class;` in a simple php file? 

If that doesn't work, I would double check your php version.
